spring:
  application:
    name: Assignment

  datasource:
    url: jdbc:postgresql://localhost:5432/Assignment
    username: phoneshop_night
    password: vichea123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
